"use client";

import { CalendarDays, Clock3, MapPin } from "lucide-react";
import { PublicShell } from "@/components/public/PublicShell";
import { EmployeePortalState } from "@/components/public/EmployeePortalState";
import { Badge } from "@/components/ui/badge";
import { useEmployeePortal } from "@/lib/client/use-employee-portal";

function formatDate(value: unknown) { const text=String(value||""); if (!text) return "Data não informada"; return new Date(`${text}T12:00:00`).toLocaleDateString("pt-BR", { weekday:"short", day:"2-digit", month:"short" }); }
function formatTime(value: unknown) { const text=String(value||""); if (!text) return "--:--"; const date=new Date(text); return Number.isNaN(date.getTime()) ? text.slice(0,5) : date.toLocaleTimeString("pt-BR", { hour:"2-digit", minute:"2-digit" }); }

export default function EmployeeSchedulePage() { const portal=useEmployeePortal(); const occurrences=portal.data?.schedule.occurrences || []; return <PublicShell eyebrow="Minha escala" title="Próximos turnos" subtitle="Horários publicados, intervalos e filial de atendimento."><EmployeePortalState loading={portal.loading} error={portal.error} reload={portal.reload}>{portal.data ? <div className="grid gap-3">{occurrences.map((item) => <article key={String(item.id)} className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.13em] text-brand-700">{formatDate(item.work_date)}</p><h2 className="mt-1 text-lg font-black text-slate-950">{item.is_day_off ? "Folga" : `${formatTime(item.starts_at)} — ${formatTime(item.ends_at)}`}</h2></div><Badge tone={item.is_day_off ? "blue" : item.status === "published" ? "green" : "yellow"}>{item.is_day_off ? "Folga" : item.status === "published" ? "Publicada" : "Planejada"}</Badge></div><div className="mt-3 grid gap-2 text-sm font-semibold text-slate-600"><p className="flex items-center gap-2"><Clock3 className="h-4 w-4 text-brand-700" /> {Array.isArray(item.intervals) && item.intervals.length ? `${item.intervals.length} intervalo(s) planejado(s)` : "Intervalo conforme jornada"}</p><p className="flex items-center gap-2"><MapPin className="h-4 w-4 text-brand-700" /> {String((Array.isArray(item.branches) ? item.branches[0]?.name : (item.branches as Record<string, unknown> | undefined)?.name) || portal.data?.branch?.name || "Filial")}</p></div></article>)}{!occurrences.length ? <div className="rounded-3xl border border-dashed border-slate-300 bg-slate-50 p-8 text-center"><CalendarDays className="mx-auto h-9 w-9 text-slate-400" /><h2 className="mt-3 font-black text-slate-900">Nenhuma escala publicada</h2><p className="mt-2 text-sm font-medium text-slate-600">Sua jornada padrão continua disponível no ponto. Quando o gestor publicar a escala, ela aparecerá aqui.</p></div> : null}</div> : null}</EmployeePortalState></PublicShell>; }
