"use client";

import { Bell, FileText, History, LogOut, ShieldCheck, UserRound } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { PublicShell } from "@/components/public/PublicShell";
import { EmployeePortalState } from "@/components/public/EmployeePortalState";
import { Button } from "@/components/ui/button";
import { publicJson } from "@/lib/client/public-api";
import { useEmployeePortal } from "@/lib/client/use-employee-portal";

export default function EmployeeProfilePage(){const portal=useEmployeePortal();const router=useRouter();async function logout(){await publicJson("/api/public/portal/logout",{method:"POST"});router.replace("/");router.refresh();}return <PublicShell eyebrow="Meu perfil" title="Conta do funcionário" subtitle="Dados básicos, comprovantes, histórico e segurança."><EmployeePortalState loading={portal.loading} error={portal.error} reload={portal.reload}>{portal.data?<div className="grid gap-4"><section className="rounded-3xl bg-slate-950 p-5 text-white"><div className="flex items-center gap-4"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-white/10"><UserRound className="h-7 w-7"/></div><div className="min-w-0"><h2 className="truncate text-xl font-black">{portal.data.employee.fullName}</h2><p className="truncate text-sm font-medium text-slate-300">{portal.data.employee.role}{portal.data.employee.sector?` • ${portal.data.employee.sector}`:""}</p><p className="mt-1 text-xs font-bold text-sky-300">{portal.data.branch?.name}</p></div></div></section><div className="grid gap-2"><Link href="/historico" className="flex min-h-16 items-center gap-3 rounded-3xl border border-slate-200 bg-white p-4 font-black text-slate-800"><History className="h-5 w-5 text-brand-700"/><span className="flex-1">Histórico de marcações</span></Link><Link href="/justificativa" className="flex min-h-16 items-center gap-3 rounded-3xl border border-slate-200 bg-white p-4 font-black text-slate-800"><FileText className="h-5 w-5 text-brand-700"/><span className="flex-1">Enviar justificativa</span></Link><div className="flex min-h-16 items-center gap-3 rounded-3xl border border-slate-200 bg-white p-4"><Bell className="h-5 w-5 text-brand-700"/><span className="flex-1 font-black text-slate-800">Notificações</span><strong className="rounded-full bg-brand-50 px-3 py-1 text-sm text-brand-700">{portal.data.unreadNotifications}</strong></div><div className="flex min-h-16 items-center gap-3 rounded-3xl border border-slate-200 bg-white p-4"><ShieldCheck className="h-5 w-5 text-emerald-600"/><span className="flex-1"><strong className="block text-sm text-slate-900">Sessão protegida</strong><span className="text-xs font-medium text-slate-500">Expira automaticamente e não armazena o PIN.</span></span></div></div><Button variant="danger" className="w-full" onClick={logout}><LogOut className="h-4 w-4"/> Sair do portal</Button></div>:null}</EmployeePortalState></PublicShell>}
